/*
 * THIS FILE WAS GENERATED BY PLOTLY.BLAZOR.GENERATOR
*/

using System.Text.Json.Serialization;
using System.Runtime.Serialization;
#pragma warning disable 1591

namespace Plotly.Blazor.LayoutLib
{
    /// <summary>
    ///     Determines the order of items shown in unified hover labels. If <c>trace</c>,
    ///     items are sorted by trace index. If &#39;value descending&#39;, items are
    ///     sorted by value from largest to smallest. If &#39;value ascending&#39;,
    ///     items are sorted by value from smallest to largest. Only applies when <c>hovermode</c>
    ///     is &#39;x unified&#39; or &#39;y unified&#39;.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Plotly.Blazor.Generator", null)]
    [JsonConverter(typeof(EnumConverter))]
    public enum HoverSortEnum
    {
        [EnumMember(Value=@"trace")]
        Trace = 0,
        [EnumMember(Value=@"value descending")]
        ValueDescending,
        [EnumMember(Value=@"value ascending")]
        ValueAscending
    }
}